import "./globals.css"
import { Roboto } from "next/font/google"

const roboto = Roboto({ weight: "400", subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="mx-12 lg:mx-24">{children}</body>
    </html>
  )
}
